<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Producto;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        //One piece
        Producto::create(['id_coleccion' => 1, 'nombre_producto' => 'Camiseta Luffy', 'precio' => 15.99, 'descripcion' => 'Camiseta licencia de One Piece en color amarillo, de manga corta y cuello redondo, confeccionada en tejido de 100% algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739158/productos/x0ltkxye3shdek9yrtyp.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739157/productos/sqot2mghrgqsbevcdizt.jpg']);
        Producto::create(['id_coleccion' => 1, 'nombre_producto' => 'Camiseta Zoro', 'precio' => 20, 'descripcion' => 'Camiseta licencia de One Piece de manga corta, cuello redondo y confeccionada en 100% algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739175/productos/l4ohma667wpwggnhlyy1.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739177/productos/asbyn3zp3nuv2ayxzlxo.jpg']);
        Producto::create(['id_coleccion' => 1, 'nombre_producto' => 'Camiseta Chopper', 'precio' => 20, 'descripcion' => 'Camiseta licencia One Piece de manga corta y cuello redondo con detalle de print y confeccionada en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739145/productos/hl29qufuhglzybk4razi.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739147/productos/ys96nt5rk6rwx3xikwkm.jpg']);
        Producto::create(['id_coleccion' => 1, 'nombre_producto' => 'Camiseta One Piece', 'precio' => 20, 'descripcion' => 'Camiseta One Piece negra con detalle de print central en contraste, de manga corta y cuello redondo, confeccionada en 100% algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739167/productos/i7wmnj9b7b3wrc5jjkdi.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739168/productos/w5pazojtsnr3zpsrvsi8.jpg']);

        //Music
        Producto::create(['id_coleccion' => 2, 'nombre_producto' => 'Camiseta Metallica', 'precio' => 20, 'descripcion' => 'Camiseta de manga corta y cuello redondo licencia Metallica con detalle de print a color y confeccionada en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686737527/productos/ax9fvmthketfelukwhsz.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686737528/productos/fdlwjnwmdwr5bbem7ecq.jpg']);
        Producto::create(['id_coleccion' => 2, 'nombre_producto' => 'Camiseta Iron Maiden', 'precio' => 20, 'descripcion' => 'Camiseta licencia Iron Maiden de manga corta y cuello redondo con detalle de print.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739069/productos/nzyyeqo1yayfecrwphcp.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739070/productos/rrbk2npqf90oc1ferkfy.jpg']);
        Producto::create(['id_coleccion' => 2, 'nombre_producto' => 'Camiseta Green Day', 'precio' => 20, 'descripcion' => 'Camiseta licencia de la banda de música Green Day con print del álbum Dookie, con diseño de manga corta y cuello redondo.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739048/productos/p9e2hmpywfywgmh3zzed.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739049/productos/q3z6g32dkpphb4fglps4.jpg']);
        Producto::create(['id_coleccion' => 2, 'nombre_producto' => 'Camiseta Foo Fighters', 'precio' => 20, 'descripcion' => 'Camiseta licencia de la banda de música Foo Fighters, de manga corta y cuello redondo, con detalle de print central y en tejido de 100% algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739038/productos/fmmdwpm2fkcpcwsph7re.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739039/productos/gtnwsgxop9fnjlxc1mxi.jpg']);

        //Tupac
        Producto::create(['id_coleccion' => 3, 'nombre_producto' => 'Camiseta Oversize Tupac', 'precio' => 20, 'descripcion' => 'Camiseta licencia Tupac con texto en contraste, de manga corta, con cuello redondo, silueta oversize y confeccionada en 100% algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739322/productos/ibzsondllq6hrwqlowcv.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739323/productos/dvhznbxgozmrtlylkubw.jpg']);
        Producto::create(['id_coleccion' => 3, 'nombre_producto' => 'Camiseta Gráfico Tupac', 'precio' => 20, 'descripcion' => 'Camiseta licencia con gráfico del rapero Tupac en contraste, de manga corta, con cuello redondo, silueta oversize y confeccionada en 100% algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739329/productos/wojfl2lhfby3qeqlihcl.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739330/productos/r4e7nan0o3dnyjqjilea.jpg']);
        Producto::create(['id_coleccion' => 3, 'nombre_producto' => 'Camiseta Contraste Tupac', 'precio' => 20, 'descripcion' => 'Camiseta licencia Tupac, de manga corta, con cuello redondo, silueta oversize y confeccionada en 100% algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739338/productos/alrydkrg5gck6tebbbya.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739339/productos/tibcxllxladueg4dxdhb.jpg']);
        Producto::create(['id_coleccion' => 3, 'nombre_producto' => 'Camiseta MATW Tupac', 'precio' => 20, 'descripcion' => 'Camiseta gris licencia Tupac con texto Me Against The World en contraste, de manga corta, con cuello redondo.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739347/productos/cd91wgdwqytogqkblttn.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739348/productos/odwc9yd01avb6q35af28.jpg']);

        //Artistic
        Producto::create(['id_coleccion' => 4, 'nombre_producto' => 'Camiseta KLIMT', 'precio' => 20, 'descripcion' => 'Camiseta licencia Gustav Klimt en color blanco con gráfico de la obra "El beso", de manga corta, con cuello redondo y en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739261/productos/za4xdctcurh3gutpqj46.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739262/productos/vk9z7vh0x2dyite0u59w.jpg']);
        Producto::create(['id_coleccion' => 4, 'nombre_producto' => 'Camiseta Ola Kanagawa', 'precio' => 20, 'descripcion' => 'Camiseta licencia con texto y print de la obra de Hokusai La Gran Ola de Kanagawa, de manga corta y con cuello redondo.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739286/productos/jickt8unjtbpfrm3srtn.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739287/productos/wa01gmqulox2c5vwuevo.jpg']);
        Producto::create(['id_coleccion' => 4, 'nombre_producto' => 'Camiseta Van Gogh', 'precio' => 20, 'descripcion' => 'Camiseta de manga corta y cuello redondo licencia de Van Gogh con detalle de print de la obra Japanese Vase.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739275/productos/vblmh6natg913j2mo880.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739277/productos/prynii8qzhhurlcpfffk.jpg']);
        Producto::create(['id_coleccion' => 4, 'nombre_producto' => 'Camiseta Katsukawa', 'precio' => 20, 'descripcion' => 'Camiseta licencia del diseñador japonés Katsukawa Shunsho con detalle de print.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739295/productos/fm2tpuddxoi8ske2wxuy.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739297/productos/ovwhxkqwteyrltqi9vlt.jpg']);

        //Rocky
        Producto::create(['id_coleccion' => 5, 'nombre_producto' => 'Camiseta Raglán Rocky', 'precio' => 20, 'descripcion' => 'Camiseta licencia Rocky Balboa con manga raglán en contraste, con cuello redondo y en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739190/productos/hbgr0kzuxjdwrl3hbapt.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739191/productos/rqmskfmrkmvga4ip3p9c.jpg']);
        Producto::create(['id_coleccion' => 5, 'nombre_producto' => 'Camiseta Beige Rocky', 'precio' => 20, 'descripcion' => 'Camiseta licencia Rocky Balboa de color beige con gráfico en contraste, de manga corta, con cuello redondo y en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739198/productos/u1knuj23ep6xda0bwfar.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739200/productos/d8djfzokissspw6k3elg.jpg']);
        Producto::create(['id_coleccion' => 5, 'nombre_producto' => 'Camiseta Negra Rocky', 'precio' => 20, 'descripcion' => 'Camiseta licencia Rocky Balboa de color negro, manga corta y en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739208/productos/cpkxxdiswj23coe0nvlx.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739209/productos/dxupydmglfdybnnjwryy.jpg']);
        Producto::create(['id_coleccion' => 5, 'nombre_producto' => 'Sudadera Rocky', 'precio' => 20, 'descripcion' => 'Sudadera licencia Rocky Balboa con capucha, bolsillo tipo canguro y detalle de rib en puños y bajo.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739218/productos/h6bsbd8lfd6kc5nsug5x.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739219/productos/owfxttmerv694nhgwuxy.jpg']);

        //Naruto
        Producto::create(['id_coleccion' => 6, 'nombre_producto' => 'Camiseta Blanca Naruto', 'precio' => 20, 'descripcion' => 'Camiseta licencia Naruto de color blanco, con bordado en contraste, de manga corta, con cuello redondo y en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739095/productos/eseacpmzbeyhmgdj8okp.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739096/productos/qwxeyxcnjya0mcd5zedd.jpg']);
        Producto::create(['id_coleccion' => 6, 'nombre_producto' => 'Camiseta Gris Naruto', 'precio' => 20, 'descripcion' => 'Camiseta licencia Naruto en color gris, de manga corta y cuello redondo con detalle de print y confeccionada en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739103/productos/tgjwz5pdiytdpkok6qzu.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739105/productos/yfusfe6wbwo5pt32jrry.jpg']);
        Producto::create(['id_coleccion' => 6, 'nombre_producto' => 'Camiseta BR Naruto', 'precio' => 20, 'descripcion' => 'Camiseta licencia de Naruto con print delantero en blanco y rosa, de manga corta y con el cuello redondo.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739116/productos/d86damarfbowbyckjroy.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739118/productos/mvga2divppgfb9ajdfhe.jpg']);
        Producto::create(['id_coleccion' => 6, 'nombre_producto' => 'Camiseta Print Naruto', 'precio' => 20, 'descripcion' => 'Camiseta licencia Naruto de manga corta y cuello redondo con detalle de print en contraste y confeccionada en algodón.', 'imagen_delantera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739126/productos/mnbhdeghjqckbjlnmykn.jpg', 'imagen_trasera' => 'https://res.cloudinary.com/daizvavk0/image/upload/v1686739127/productos/ckdrrvgpkuco9ix3tjge.jpg']);



    }
}
