@extends('layouts.app')

@section('content')
    <div class="contenido col-10">
        <h1 class="mb-4 mt-4"><strong>AVISO LEGAL</strong></h1>
     <ol>
         <strong><li class="mb-3">DATOS IDFENTIFICATIVOS</li></strong>
         <p>El empresario titular del sitio web grandline.com (en adelante, “el sitio web) es VÍCTOR BÁEZ ESCALERA, con DNI 23880313B, inscrito en el registro de empresarios individuales, con las siguientes referencias __________________________</p>
         <p>La tienda del sitio Web es responsabilidad de VÍCTOR BÁEZ ESCALERA, cuyos datos aparecen arriba.</p>
         <strong><li class="mb-3">CONTACTO</li></strong>
         <p>Si desea usted contactar con nosotros, utilice las vías de contacto identificadas en la sección Contacto. Para cuestiones relacionadas con la tienda del Sitio Web, diríjase a hello@grandline.com.</p>
         <strong><li class="mb-3">USO DEL SITIO WEB</li></strong>
         <p>El uso del Sitio Web le atribuye a usted la condición de usuario. El usuario acepta, por el mero uso, las condiciones aquí reflejadas.</p>
         <p>El usuario se compromete a hacer un uso adecuado y diligente de los contenidos y servicios del Sitio Web, de conformidad con la ley, la moral, el orden público y lo dispuesto en estas condiciones de uso, y deberá abstenerse de utilizar dichos contenidos y servicios en cualquier forma que pueda impedir, dañar o deteriorar el normal funcionamiento y disfrute del Sitio Web por parte de otros usuarios o que pudiera lesionar o causar daños a los bienes y derechos de VÍCTOR BÁEZ ESCALERA, de otros usuarios o, en general, de cualquier tercero.</p>
         <p>Además, y sin que esta enumeración limite el alcance general de la obligación dispuesta en el párrafo anterior, el usuario se obliga en la utilización del Sitio Web a: (a) no introducir o difundir contenidos o información de carácter racista, sexista, xenófobo, pornográfico, injurioso, obsceno, que suponga apología del terrorismo, incite a la violencia o atente contra los derechos humanos, o que de cualquier forma atente contra la moral, el orden público, los derechos fundamentales, las libertades públicas, el honor, la intimidad o la imagen de terceros y, en general, la normativa vigente; (b) no provocar daños en los sistemas físicos y lógicos de VÍCTOR BÁEZ ESCALERA o de terceras personas, ni introducir, almacenar o difundir mediante el Sitio Web ningún programa, dato, virus informático, código o cualesquiera otros sistemas físicos o lógicos que sean susceptibles de provocar los daños mencionados; (c) no utilizar el Sitio Web, los contenidos y en particular la información obtenida a través del Sitio Web, para remitir publicidad, enviar mensajes con fines de venta directa o con cualquier otro fin comercial, ni para recoger o almacenar datos personales de terceros.</p>
         <strong><li class="mb-3">PROPIEDAD INTELECTUAL E INDUSTRIAL</li></strong>
         <p>El usuario reconoce que todos los elementos contenidos o utilizados en el Sitio Web (a título de ejemplo: imágenes, software, textos y marcas) están protegidos por derechos de propiedad intelectual e industrial de VÍCTOR BÁEZ ESCALERA o sus respectivos titulares o licenciatarios, y se compromete a respetar tales derechos.</p>
         <p>Salvo que la ley disponga lo contrario, el usuario no podrá reproducir, transformar, modificar, desensamblar, realizar ingeniería inversa, distribuir, alquilar, prestar, poner a disposición, o permitir el acceso al público a través de cualquier modalidad de comunicación pública de ninguno de los elementos referidos en el párrafo anterior, sin la autorización de los titulares de los derechos correspondientes.</p>
         <strong><li class="mb-3">EXCLUSIÓN DE GARANTÍAS Y RESPONSABILIDAD</li></strong>
         <p>VÍCTOR BÁEZ ESCALERA únicamente responderá de los daños que el usuario pueda sufrir como consecuencia de la utilización del Sitio Web cuando dichos daños sean imputables a una actuación dolosa de VÍCTOR BÁEZ ESCALERA. El usuario reconoce y acepta que la utilización del Sitio Web se realiza bajo su entero riesgo y su entera responsabilidad.</p>
         <p>VÍCTOR BÁEZ ESCALERA actuará diligentemente, según los usos generalmente aceptados en el sector, para evitar la presencia en el Sitio Web de virus u otros elementos lesivos que pudieran causar alteraciones en el sistema informático del usuario, pero no puede garantizar la ausencia de tales elementos, no siendo responsable por los daños y perjuicios que ello pudiera ocasionar.</p>
         <p>Con carácter meramente enunciativo y no limitativo, VÍCTOR BÁEZ ESCALERA no se hará responsable de los perjuicios que se pudieran derivar de: (a) inferencias, omisiones, interrupciones, virus informáticos, averías y/o desconexiones en los equipos y dispositivos del usuario, motivados por causas ajenas a VÍCTOR BÁEZ ESCALERA; (b) interrupciones o bloqueos en el uso causados por deficiencias o sobrecargas de Internet o en otros sistemas electrónicos; (c) perjuicios que causados por terceras personas mediante intromisiones ilegítimas en el Sitio Web; y (d) la imposibilidad de dar el servicio o permitir el acceso por causas no imputables a VÍCTOR BÁEZ ESCALERA, debidas al usuario, a terceros, o a supuestos de fuerza mayor.</p>
         <strong><li class="mb-3">MODIFICACIÓN DE LAS PRESENTES CONDICIONES</li></strong>
         <p>VÍCTOR BÁEZ ESCALERA podrá modificar en cualquier momento estas condiciones de uso y publicará las nuevas condiciones de uso en el Sitio Web de forma que el usuario pueda conocerlas antes de proceder al uso del Sitio Web. La utilización del Sitio Web una vez modificadas las condiciones de uso significará la aceptación por parte del usuario de las condiciones de uso así modificadas.</p>
         <strong><li class="mb-3">LEGISLACIÓN APLICABLE Y FUERO</li></strong>
         <p>Las disposiciones contenidas en las presentes condiciones de uso se regirán e interpretarán de conformidad con la normativa española y cualquier controversia se someterá a los juzgados y tribunales de la ciudad de Sevilla.</p>
     </ol>

    </div>
@endsection
